# SPDX-License-Identifier: GPL-2.0
#
# (C) Copyright 2012 Stephen Warren

$(info [Build] arch/arm/mach-bcm283x/Makefile)

obj-$(CONFIG_BCM2835) += lowlevel_init.o
obj-y	+= init.o reset.o mbox.o msg.o phys2bus.o
