# SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2018 Alexander Graf <agraf@suse.de>
#
# https://spdx.org/licenses

obj-$(CONFIG_PINCTRL_NF283X) += pinctrl-nf283x.o
obj-$(CONFIG_PINCTRL_NF6838) += pinctrl-nf6838.o
