# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_NAND_NFSNAND_6368) += bcm6368_nand.o
obj-$(CONFIG_NAND_NFSNAND_63158) += bcm63158_nand.o
obj-$(CONFIG_NAND_NFSNAND_6753) += bcm6753_nand.o
obj-$(CONFIG_NAND_NFSNAND_68360) += bcm68360_nand.o
obj-$(CONFIG_NAND_NFSNAND_6838) += bcm6838_nand.o
obj-$(CONFIG_NAND_NFSNAND_6858) += bcm6858_nand.o
obj-$(CONFIG_NAND_NFSNAND_IPROC) += iproc_nand.o
obj-$(CONFIG_NAND_NFSNAND) += nfsnand.o
obj-$(CONFIG_NAND_NFSNAND) += nfsnand_compat.o
